source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

project 'Sonar'

target 'Sonar_Example' do
  pod "Sonar", :path => "../"
end.

target 'Sonar_Tests' do
  pod "Sonar", :path => "../"
end
