source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

def setup_actions
  use_frameworks!
  pod 'Sonar', :path => "../"
end

target 'Sonar_Example' do
  setup_actions
end

target 'Sonar_Tests' do
  setup_actions
end
